#! ../.venv/bin/python3
# -*- coding: utf-8 -*-

import sqlite3
import http.server
import socketserver


class MyHttpRequestHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        # Sending an '200 OK' response
        self.send_response(200)

        # Setting the header
        self.send_header("Content-type", "text/html")

        # Whenever using 'send_header', you also have to call 'end_headers'
        self.end_headers()

        # Some custom HTML code, possibly generated by another function
        html = f"""
                <!DOCTYPE html>
                <html>
                
                <head>
                    <title>
                        Realtime sensor reading
                    </title>
                    
                    <script>
                        function autoRefresh() {{
                            window.location = window.location.href;
                        }}
                        setInterval('autoRefresh()', 1000);
                    </script>
                </head>
                
                <body>
                    <h1>Sensor output!</h1>
                </body>
                
                </html>"""

        # Writing the HTML contents with UTF-8
        self.wfile.write(bytes(html, "utf8"))

        return


# Create an object of the above class
handler_object = MyHttpRequestHandler

PORT = 8000
my_server = socketserver.TCPServer(("", PORT), handler_object)

# Star the server
my_server.serve_forever()


# Setup connection to the database
conn = sqlite3.connect("./sps30/sps30.db")
c = conn.cursor()

row = c.execute("""SELECT * FROM sps30 ORDER BY actual_time DESC LIMIT 1""").fetchone()


conn.close()
